"use strict";

const fs = require("fs");
const path = require("path");

describe("operator copy drift guards", () => {
  const commandCenter = fs.readFileSync(
    path.resolve(process.cwd(), "operator/operator-command-center.js"),
    "utf8"
  );
  const moneyWorkspace = fs.readFileSync(
    path.resolve(process.cwd(), "operator/operator-money-workspace.js"),
    "utf8"
  );

  test("keeps the dashboard money language calm and plain", () => {
    expect(commandCenter).toContain("Get your first wins");
    expect(commandCenter).toContain("Open balances");
    expect(commandCenter).toContain("Payment follow-up due");
    expect(commandCenter).not.toContain("Outstanding money");
    expect(commandCenter).not.toContain("Go â†’");
  });

  test("keeps money workspace summaries free of visible encoding drift", () => {
    expect(moneyWorkspace).toContain("1-30 days overdue");
    expect(moneyWorkspace).toContain("Generated by ProofLink - prooflink.co");
    expect(moneyWorkspace).not.toContain("â€¢");
    expect(moneyWorkspace).not.toContain("â€“");
  });
});
