"use strict";

const fs = require("fs");
const path = require("path");

describe("operator copy drift guards", () => {
  const commandCenter = fs.readFileSync(
    path.resolve(process.cwd(), "operator/operator-command-center.js"),
    "utf8"
  );
  const moneyWorkspace = fs.readFileSync(
    path.resolve(process.cwd(), "operator/operator-money-workspace.js"),
    "utf8"
  );
  const walkthrough = fs.readFileSync(
    path.resolve(process.cwd(), "operator/walkthrough.js"),
    "utf8"
  );

  test("keeps the dashboard money language calm and plain", () => {
    expect(commandCenter).toContain("Get your first wins");
    expect(commandCenter).toContain("Open balances");
    expect(commandCenter).toContain("Payment follow-up due");
    expect(commandCenter).not.toContain("Outstanding money");
    expect(commandCenter).not.toContain("Go Ã¢â€ â€™");
  });

  test("keeps money workspace summaries free of visible encoding drift", () => {
    expect(moneyWorkspace).toContain("1-30 days overdue");
    expect(moneyWorkspace).toContain("Generated by ProofLink - prooflink.co");
    expect(moneyWorkspace).not.toContain("Ã¢â‚¬Â¢");
    expect(moneyWorkspace).not.toContain("Ã¢â‚¬â€œ");
  });

  test("keeps the guided tour in owner-friendly language", () => {
    expect(walkthrough).toContain("business story current here");
    expect(walkthrough).toContain("account details stay visible but locked");
    expect(walkthrough).not.toContain("application or account-record data");
    expect(walkthrough).not.toContain("approved record");
    expect(walkthrough).not.toContain("from this workspace");
  });
});
